name: 'Mention Reviewers'
description: 'This action creates a string that mentions all the reviewers for a pull request.'
inputs:
  event:  # id of input
    description: 'The github Event.'
    required: true
outputs:
  mentions: # id of output
    description: 'A string that mentions all the reviewers.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.event }}
